# use_frameworks!
platform :ios, '8.0'


target 'KFXLocation_Example' do
  pod 'KFXLocation', :path => '../'
    
  pod 'KFXCore'
  pod 'KFXAdditions'
  pod 'KFXUtilities'

  target 'KFXLocation_Tests' do
    inherit! :search_paths

    
  end
end
