platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'KFXLocation_Example' do
  pod 'KFXLocation', :path => '../'

	### If using from trunk
	source 'https://cdn.cocoapods.org/'
  pod 'KFXCore'
  pod 'KFXAdditions'
  pod 'KFXUtilities'

  target 'KFXLocation_Tests' do
    inherit! :search_paths

    
  end
end
