use_frameworks!

target 'KFXLocation_Example' do
  pod 'KFXLocation', :path => '../'
  
  ## Sources
  ### If using private pods
  source 'https://bitbucket.org/kfx_pods/kfxsharedspecs.git'
  
  pod 'KFXAdditions'
  pod 'KFXCore'
  
  ### If using from trunk
  source 'http://github.com/Cocoapods/Specs.git'


  target 'KFXLocation_Tests' do
    inherit! :search_paths

    
  end
end
